### ISSUE TITLE
Error on Recognize

### ISSUE THREAD

**Issue by daniazar** [kairosinc/Kairos-SDK-Javascript#1]
On line 195 of kairos.js

  var data = { 'image' : image_data , 'gallery_name' : gallery_id, 'subject_id' : subject_id};

subject_id should be removed.

As it is a recognize function and you don't know who the subject is.

That line should be:

  var data = { 'image' : image_data , 'gallery_name' : gallery_id};

**Comment by sean5hc** [comment]
Hi Daniazar, 

Thanks for bringing this to our attention. Will make the necessary update.

Best,
Eric
