### ISSUE TITLE
removeGallery throws error: options is not defined

### ISSUE THREAD

**Issue by davidglivar** [kairosinc/Kairos-SDK-Javascript#2]
Relevant line: https://github.com/kairosinc/Kairos-SDK-Javascript/blob/master/kairos.js#L349

**Comment by coleca** [comment]
@steverucker Can you look into this?

**Comment by steverucker** [comment]
This error is fixed.  The options argument was not being passed to the removeGallery and removeSubjectFromGallery methods.
