### ISSUE TITLE
response.responseText return null

### ISSUE THREAD

**Issue by damaragung** [kairosinc/Kairos-SDK-Javascript#3]
Hi ,, 

It's my first time using this api,, and i try to use quick demo. When i drop the image,, I found this error. 

![1455181926612](https://cloud.githubusercontent.com/assets/6584634/12972784/76cc4c1a-d0da-11e5-8aa1-c8deb58307af.jpg)

![1455183613629](https://cloud.githubusercontent.com/assets/6584634/12973328/2dcbe2c4-d0de-11e5-84b2-ddc7a4c052de.jpg)

maybe i forgot setup something, but i don't have any idea. 

Thank you

**Comment by coleca** [comment]
It should be all set now.  We had an issue with our SSL endpoint that is now fixed.  

We have added additional monitoring to prevent that issue in the future.

Thanks,

**Comment by damaragung** [comment]
yes,, thank you very much
