### ISSUE TITLE
Analyzing videos

### ISSUE THREAD

**Issue by shyamchandranmec** [kairosinc/Kairos-SDK-Javascript#6]
Hi,
 Can I analyze videos with this sdk? I need to record emotions of a user via a browser and webcam. Couldn't find much about this in the docs related to sdk.
Please help.
Thanks in advance

**Comment by coleca** [comment]
Hi,

Check out https://github.com/kairosinc/api-examples we have some examples in there around emotions.  The code is in PHP, but the actual recording of the webcam is in JS, so you could use that.

**Comment by shyamchandranmec** [comment]
@coleca Will the js sdk give the emotion results without calling the api? Or do I have to record the video and send it to the api?

**Comment by coleca** [comment]
You would record the video and send to the API.

**Comment by shyamchandranmec** [comment]
@coleca Thanks for the quick response. Will try it out.
